<template>
    <div>
        <h1>Privacy & Terms</h1>
        <p>By using the blargbot API, you acknowledge and agree to the following:</p>
        <h2>Terms</h2>
        <ul>
            <li>The blargbot API ("Service") is a web-based Application Programming Interface ("API") which serves generated images based on user input.</li>
            <li>Use of the Service is restricted and monitored by use of Authentication Tokens ("Tokens"). A Token is required to access the API, and is tied explicitly to a Discord Account ("User").</li>
            <li>Being in the Discord Guild "Cat Town" (
                <a href='https://discord.gg/015GVxZxI8rtlJgXF'>invite</a> ) is a service requirement for communication purposes. Leaving the Guild may cause your Token to be invalidated.
            </li>
            <li>Abusing or exploiting the Service in any way may result in the Token being revoked with or without warning. "Abuse" may be characterized, but not limited to, the following:
                <ul>
                    <li>Spamming the server with requests (ex. DDoS)</li>
                    <li>Sharing a Token</li>
                    <li>Creating a public API wrapper which forwards all requists to the Service</li>
                </ul>
            </li>
            <li>Credit for the images generated by the Service would be nice, but not required.</li>
        </ul>

        <h2>Privacy</h2>
        <ul>
            <li>The Service may collect diagnostic and statistical information by tracking the API calls ("Usage") a User makes. This information will not be shared in a manner which would publically link a User to it's Usage.</li>
        </ul>
    </div>
</template>

<script>
export default {};
</script>

<style>
</style>
